services:
  - type: web
    name: review-analyser
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LANGUAGE_ENDPOINT
        sync: false
      - key: LANGUAGE_KEY
        sync: false
